const ScreenNames = {
  LOGIN: "Login",
  HOME: "Home",
  WELCOME: "Welcome",
  REGISTER: "Register",
  FORGOTPASSWORD: "ForgotPassword",
  OTPSCREEN: "OTPScreen",
  RESETPASSWORD: "ResetPassword",
  SMSGATEWAY: "SMSGateWay",
  PROFILE: "Profile",
  CONTACTS: "Contacts",
  SETTINGS: "SettingsScreen",
  MESSAGESHOMESCREEN: "MessagesHomeScreen",
  SIMMANAGEMENT: "SimManagement",
  BOTTOMTAB: "BottobTab",
  NEWCONTACT: "NewContact",
  EDITCONTACT: "EditContact",
  VIEWCONTACT: "ViewContact",
  PROFILEVIEWEMAIL: "ProfileViewEmail",
  EDITEMAIL: "EditEmail",
  AUTOREPLY: "AutoReply",
  EDITSIMNAME: "EditSimName",
  CHAT: "Chat",
  TEXTSIZE: "TextSize",
  MESSAGEQUICKSELECT: "MessageQuickSelect",
  SELECTBROADCASTNUMBER: "SelectBroadcastNumber",
  BROADCAST: "BroadCast",
  CONTACTQUICKSELECT: "ContactQuickSelect",
};
export default ScreenNames;
