export {default as EditPen} from './editPen';
export {default as SimCard} from './simCard';
export {default as ChatAvatar} from './chatAvatar';
export { default as ProfileTabIcon } from "./profile-tab-icon";
export { default as Camera } from "./camera";
export { default as DownArrow } from "./down-arrow";
export { default as ChatIcon } from "./chat";
export { default as EditCamera } from "./editCamera";
export { default as BlackList } from "./blacklist";
export { default as Archive } from "./archive";
export { default as Setting } from "./setting";
export { default as Signal } from "./signal";
export { default as EyeOpen } from "./eyeOpen";
export { default as WhiteTick } from "./whiteTick";
export { default as SimCard2 } from "./simCard2";
export { default as CrossIcon } from "./crossIcon";
export { default as CopyIcon } from "./copyIcon";
export { default as DeleteIcon } from "./delete";
export { default as SwitchOn } from "./switchOn";
export { default as SwitchOff } from "./switchOff";
export { default as SearchIcon } from "./search";
export { default as MuteIcon } from "./mute";
export { default as CrossIcon2 } from "./cross";
export { default as ChatIconTwo } from "./chatIcon";
export { default as SimCardNitification } from "./simCardNotification";
export { default as VerticalSimCard } from "./vertical-simCard";
export { default as PinIcon } from "./pin";
export { default as AddContact } from "./add-contact";
